export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const GET_RESTAURANT_CITY_REQUEST = "GET_RESTAURANT_CITY_REQUEST";
export const GET_RESTAURANT_CITY_SUCCESS = "GET_RESTAURANT_CITY_SUCCESS";
